name: speech_stream
description: A Flutter plugin for streaming speech audio data in segments
version: 0.0.1
homepage: https://github.com/hn12404988/flutter_speech_stream

environment:
  sdk: ^3.0.0
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: vn.casperpas.sound_stream
        pluginClass: SoundStreamPlugin
      ios:
        pluginClass: SoundStreamPlugin